# Generated by Django 4.1.4 on 2022-12-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0003_rename_userid_passenger_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.DecimalField(decimal_places=8, max_digits=8)),
                ('remaining_capacity', models.DecimalField(decimal_places=8, max_digits=8)),
                ('isfull', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_date', models.DateTimeField()),
                ('end_time_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='ticket.station')),
                ('start_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='ticket.station')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_train', to='ticket.train')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=8, null=True)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passtick', to='passenger.passenger')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.trip')),
            ],
        ),
    ]
