# Generated by Django 4.1.4 on 2022-12-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='remaining_capacity',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='train',
            name='total_capacity',
            field=models.IntegerField(max_length=4),
        ),
    ]
