# Generated by Django 4.1.4 on 2022-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_train_remaining_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='remaining_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='total_capacity',
            field=models.IntegerField(),
        ),
    ]
