# Generated by Django 4.1.4 on 2022-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_train_remaining_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
