# Generated by Django 4.1.4 on 2022-12-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_trip_remaining_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='remaining_capacity',
            field=models.IntegerField(default=-1),
        ),
    ]
