# Generated by Django 4.1.4 on 2022-12-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='remaining_capacity',
        ),
    ]
