# Generated by Django 4.1.4 on 2022-12-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_passenger_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='userID',
            new_name='user',
        ),
    ]
